// Code generated by "stringer -type Token"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[IDENT-1]
	_ = x[PACKAGE-2]
	_ = x[IMPORT-3]
	_ = x[VAR-4]
	_ = x[COMMENT-5]
	_ = x[LPAREN-6]
	_ = x[RPAREN-7]
	_ = x[COMMA-8]
	_ = x[ASSIGN-9]
	_ = x[STRING-10]
}

const _Token_name = "ILLEGALIDENTPACKAGEIMPORTVARCOMMENTLPARENRPARENCOMMAASSIGNSTRING"

var _Token_index = [...]uint8{0, 7, 12, 19, 25, 28, 35, 41, 47, 52, 58, 64}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
