run:
  skip-dirs:
    - infra/builds
linters-settings:
  staticcheck:
    checks: ["all"]
  stylecheck:
    checks: ["all", "-ST1003"]
  funlen:
    lines: 200
  cyclop:
    max-complexity: 14
  varnamelen:
    max-distance: 25
    ignore-names:
      - err # error values
      - db # database connections
      - ec # ent model client
      - tx # database transactions
      - OR # or token
      - GO # go token
      - IF # if token
linters:
  enable-all: true
  disable:
    - exhaustivestruct # deprecated
    - exhaustruct # CDK has large structs we use partially
    - golint # deprecated
    - varcheck # deprecated
    - structcheck # deprecated
    - interfacer # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - ifshort # deprecated
    - maligned # deprecated
    - deadcode # deprecated
    - gochecknoinits # frameworks and magefile use init responsibly
    - gci # no way to automate this in the vscode so default ordering is good enough
    - ireturn # our oapi implementations return interfaces all the time
    - depguard # too agressive
    - tagliatelle # we have lots of aws tags that don't follow the standards
    - testpackage # this is not wrong by definition
    - interfacebloat # too strict

issues:
  include:
    - EXC0015 # warn for lack of package comment
    - EXC0013 # warn for lack of package comment
    - EXC0012 # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0014 # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments
  exclude-rules:
    - path: "internal/token/token.go"
      linters:
        - funlen
        - cyclop
        - revive
    - path: 'internal/scanner/.*\.go'
      linters:
        - cyclop
        - gomnd
        - nonamedreturns
        - funlen
        - gocognit
        - gocyclo
        - nlreturn
        - wsl
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - forcetypeassert
        - goerr113
