// Code generated by "stringer -type Token -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[IDENT-2]
	_ = x[COMMENT-3]
	_ = x[BREAK-4]
	_ = x[CASE-5]
	_ = x[CHAN-6]
	_ = x[CONST-7]
	_ = x[CONTINUE-8]
	_ = x[DEFAULT-9]
	_ = x[DEFER-10]
	_ = x[ELSE-11]
	_ = x[FALLTHROUGH-12]
	_ = x[FOR-13]
	_ = x[FUNC-14]
	_ = x[GO-15]
	_ = x[GOTO-16]
	_ = x[IF-17]
	_ = x[IMPORT-18]
	_ = x[INTERFACE-19]
	_ = x[MAP-20]
	_ = x[PACKAGE-21]
	_ = x[RANGE-22]
	_ = x[RETURN-23]
	_ = x[SELECT-24]
	_ = x[STRUCT-25]
	_ = x[SWITCH-26]
	_ = x[TYPE-27]
	_ = x[VAR-28]
	_ = x[INT-29]
	_ = x[FLOAT-30]
	_ = x[STRING-31]
	_ = x[SEMICOLON-32]
	_ = x[COLON-33]
	_ = x[PERIOD-34]
	_ = x[ELLIPSIS-35]
	_ = x[COMMA-36]
	_ = x[DEFINE-37]
	_ = x[ARROW-38]
	_ = x[INC-39]
	_ = x[DEC-40]
	_ = x[ASSIGN-41]
	_ = x[EQL-42]
	_ = x[NEQ-43]
	_ = x[NOT-44]
	_ = x[AND_NOT-45]
	_ = x[AND-46]
	_ = x[XOR-47]
	_ = x[OR-48]
	_ = x[LAND-49]
	_ = x[LOR-50]
	_ = x[LPAREN-51]
	_ = x[RPAREN-52]
	_ = x[LBRACK-53]
	_ = x[RBRACK-54]
	_ = x[LBRACE-55]
	_ = x[RBRACE-56]
	_ = x[LSS-57]
	_ = x[LEQ-58]
	_ = x[SHL-59]
	_ = x[GTR-60]
	_ = x[GEQ-61]
	_ = x[SHR-62]
	_ = x[QUO-63]
	_ = x[MUL-64]
	_ = x[ADD-65]
	_ = x[SUB-66]
	_ = x[REM-67]
	_ = x[QUO_ASSIGN-68]
	_ = x[MUL_ASSIGN-69]
	_ = x[ADD_ASSIGN-70]
	_ = x[SUB_ASSIGN-71]
	_ = x[AND_NOT_ASSIGN-72]
	_ = x[AND_ASSIGN-73]
	_ = x[OR_ASSIGN-74]
	_ = x[SHR_ASSIGN-75]
	_ = x[SHL_ASSIGN-76]
	_ = x[REM_ASSIGN-77]
	_ = x[XOR_ASSIGN-78]
}

const _Token_name = "#illegal#eof#ident#commentbreakcasechanconstcontinuedefaultdeferelsefallthroughforfuncgogotoifimportinterfacemappackagerangereturnselectstructswitchtypevar<int><float><string>;:....,:=<-++--===!=!&^&^|&&||()[]{}<<=<<>>=>>/*+-%/=*=+=-=&^=&=|=>>=<<=%=^="

var _Token_index = [...]uint8{0, 8, 12, 18, 26, 31, 35, 39, 44, 52, 59, 64, 68, 79, 82, 86, 88, 92, 94, 100, 109, 112, 119, 124, 130, 136, 142, 148, 152, 155, 160, 167, 175, 176, 177, 178, 181, 182, 184, 186, 188, 190, 191, 193, 195, 196, 198, 199, 200, 201, 203, 205, 206, 207, 208, 209, 210, 211, 212, 214, 216, 217, 219, 221, 222, 223, 224, 225, 226, 228, 230, 232, 234, 237, 239, 241, 244, 247, 249, 251}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
