// Code generated by "stringer -type ExpectCode -linecomment"; DO NOT EDIT.

package lexerr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExpectedPackageKeyword-0]
	_ = x[ExpectedImportKeyword-1]
	_ = x[ExpectedFuncKeyword-2]
	_ = x[ExpectedVarKeyword-3]
	_ = x[ExpectedConstKeyword-4]
	_ = x[ExpectedLetter-5]
	_ = x[ExpectedWhiteSpace-6]
	_ = x[ExpectedComment-7]
	_ = x[FirstCommentCharacter-8]
	_ = x[SecondCommentCharacter-9]
	_ = x[ExpectedLeftParenthesis-10]
	_ = x[ExpectedRightParenthesis-11]
	_ = x[ExpectedStringLiteral-12]
	_ = x[ExpectedDoubleQuote-13]
	_ = x[ExpectedComma-14]
}

const _ExpectCode_name = "'package' keyword'import' keyword'func' keyword'var' keyword'const' keywordletterwhite spacecommentfirst comment charactersecond comment characterleft parenthesisright parenthesisstring literaldouble quotecomma"

var _ExpectCode_index = [...]uint8{0, 17, 33, 47, 60, 75, 81, 92, 99, 122, 146, 162, 179, 193, 205, 210}

func (i ExpectCode) String() string {
	if i < 0 || i >= ExpectCode(len(_ExpectCode_index)-1) {
		return "ExpectCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExpectCode_name[_ExpectCode_index[i]:_ExpectCode_index[i+1]]
}
